name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Tool restore
      run: dotnet tool restore
    - name: Fantomas check
      run: dotnet fantomas . --check
    - name: Package tool
      run: dotnet pack --properties Configuration=Release
    - name: Generate the documentation
      run: dotnet fsdocs build --projects elmish-land.fsproj --properties Configuration=Release
    - name: Upload documentation
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
